package new_kasir;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Faiz
 */

public class login extends javax.swing.JFrame {
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
    

    /**
     * Creates new form LOGIN
     */
    public login() {
        initComponents();
        setLocationRelativeTo(this);
        k.connect();
    }
    class user{
        int id_user, id_level;
        String username, password, nama_user;
        
        public user(){
            this.id_user = 0;
            this.username = TXT_USERNAME.getText();
            this.password = TXT_PASSWORD.getText();
            this.nama_user = "";
            this.id_level = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXT_USERNAME = new javax.swing.JTextField();
        BTN_LOGIN = new javax.swing.JButton();
        TXT_PASSWORD = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(810, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 65)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 39, 428, 85));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel3.setText("USERNAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 275, 54));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel4.setText("PASSWORD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 235, 275, 58));

        TXT_USERNAME.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        TXT_USERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_USERNAMEActionPerformed(evt);
            }
        });
        getContentPane().add(TXT_USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 340, -1));

        BTN_LOGIN.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        BTN_LOGIN.setText("LOGIN");
        BTN_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LOGINActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 304, 347, 55));

        TXT_PASSWORD.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        getContentPane().add(TXT_PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 340, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Downloads\\Coklat muda lucu estetik gambar makanan imut wallpaper desktop.png")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_USERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_USERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_USERNAMEActionPerformed

    private void BTN_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LOGINActionPerformed
        user u = new user();
        try {
            this.stat = k.getCon().prepareStatement("SELECT * FROM `user` WHERE "
                    + "username='"+u.username+"' and password='"+u.password+"';");
            this.rs = this.stat.executeQuery();
            while (rs.next()){
                u.id_level = rs.getInt("id_level");
            }
            if(u.id_level==0){
                JOptionPane.showMessageDialog(null, "AKUN TIDAK DITEMUKAN");               
            }else{
                switch(u.id_level){
                    case 1 :
                        MenuRegistrasi reg = new MenuRegistrasi();
                        reg.setVisible(true);
                        this.setVisible(false);
                        JOptionPane.showMessageDialog(null, "LOGIN BERHASIL SEBAGAI ADMIN");
                        break;
                    case 2 :
                        MenuTransaksi tran = new MenuTransaksi();
                        tran.setVisible(true);
                        this.setVisible(false);
                        JOptionPane.showMessageDialog(null, "LOGIN BERHASIL SEBAGAI KASIR");
                        break;
                    case 3 :
                        MenuTransaksi tran2 = new MenuTransaksi();
                        tran2.setVisible(true);
                        this.setVisible(false);
                        tran2.btn_bayar.setEnabled(true);
                        JOptionPane.showMessageDialog(null, "LOGIN BERHASIL SEBAGAI OWNER");
                        break;
                    case 4 :
                        MenuMasakan masak = new MenuMasakan();
                        masak.setVisible(true);
                        this.setVisible(false);
                        JOptionPane.showMessageDialog(null, "LOGIN BERHASIL SEBAGAI CUSTOMER");
                        masak.BTN_LOGOUT.setEnabled(true);                       
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_BTN_LOGINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_LOGIN;
    private javax.swing.JPasswordField TXT_PASSWORD;
    private javax.swing.JTextField TXT_USERNAME;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
