package new_kasir;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Faiz
 */
public class MenuMasakan extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi ();
    

    /**
     * Creates new form MenuMasakan
     */
    public MenuMasakan() {
        initComponents();
        setLocationRelativeTo(this);
        k.connect();
        refreshTable();
    }

    class masakan extends MenuMasakan{
        int id_masakan, harga;
        String nama_masakan, status;
        
        public masakan(){
             this.nama_masakan = TXT_NAMAMASAKAN.getText();
             this.harga = Integer.parseInt(TXT_HARGA.getText());
             this.status = COMBO_STATUS.getSelectedItem().toString();             
        }
        
    }
    
    public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("ID MASAKAN");
        model.addColumn("NAMA MASAKAN");
        model.addColumn("HARGA");
        model.addColumn("STATUS MASAKAN");
        TABLE_MASAKAN.setModel(model);
        
        try {
            this.stat = k.getCon().prepareStatement("SELECT * FROM `masakan`");
            this.rs = this.stat.executeQuery();
            while (rs.next()){
                Object[] data = {
                    rs.getInt("id_masakan"),
                    rs.getString("nama_masakan"),
                    rs.getInt("harga"),
                    rs.getString("status")
                };
                model.addRow(data);
            }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        TXT_IDMASAKAN.setText("");
        TXT_NAMAMASAKAN.setText("");
        TXT_HARGA.setText("");
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXT_IDMASAKAN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXT_NAMAMASAKAN = new javax.swing.JTextField();
        TXT_HARGA = new javax.swing.JTextField();
        COMBO_STATUS = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE_MASAKAN = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BTN_INPUT = new javax.swing.JButton();
        BTN_UPDATE = new javax.swing.JButton();
        BTN_DELETE = new javax.swing.JButton();
        BTN_REGISTRASI = new javax.swing.JButton();
        BTN_LOGOUT = new javax.swing.JButton();
        BTN_TRANSAKSI = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" MASAKAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 400, 73));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID MASAKAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 93, 228, -1));

        TXT_IDMASAKAN.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        TXT_IDMASAKAN.setEnabled(false);
        getContentPane().add(TXT_IDMASAKAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 90, 374, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA MASAKAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 138, 228, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HARGA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 183, 228, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STATUS MASAKAN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 230, 228, -1));

        TXT_NAMAMASAKAN.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        getContentPane().add(TXT_NAMAMASAKAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 135, 374, -1));

        TXT_HARGA.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        getContentPane().add(TXT_HARGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 180, 374, -1));

        COMBO_STATUS.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        COMBO_STATUS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TERSEDIA", "HABIS" }));
        getContentPane().add(COMBO_STATUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 230, 374, 41));

        TABLE_MASAKAN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TABLE_MASAKAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLE_MASAKANMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLE_MASAKAN);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 716, 150));

        BTN_INPUT.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        BTN_INPUT.setText("INPUT");
        BTN_INPUT.setEnabled(false);
        BTN_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_INPUTActionPerformed(evt);
            }
        });

        BTN_UPDATE.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        BTN_UPDATE.setText("UPDATE");
        BTN_UPDATE.setEnabled(false);
        BTN_UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_UPDATEActionPerformed(evt);
            }
        });

        BTN_DELETE.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        BTN_DELETE.setText("DELETE");
        BTN_DELETE.setEnabled(false);
        BTN_DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DELETEActionPerformed(evt);
            }
        });

        BTN_REGISTRASI.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        BTN_REGISTRASI.setText("MENU REGISTRASI");
        BTN_REGISTRASI.setEnabled(false);
        BTN_REGISTRASI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REGISTRASIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTN_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_REGISTRASI, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_REGISTRASI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 283, -1, -1));

        BTN_LOGOUT.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        BTN_LOGOUT.setText("LOGOUT");
        BTN_LOGOUT.setEnabled(false);
        BTN_LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LOGOUTActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 0, 146, 45));

        BTN_TRANSAKSI.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        BTN_TRANSAKSI.setText("MENU TRANSAKSI");
        BTN_TRANSAKSI.setEnabled(false);
        BTN_TRANSAKSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_TRANSAKSIActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_TRANSAKSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 45));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Downloads\\Daftar Menu Makanan Food Instagram Post.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LOGOUTActionPerformed
        login l = new login();
        BTN_LOGOUT.setEnabled(true);
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_LOGOUTActionPerformed

    private void BTN_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_INPUTActionPerformed
        try {
            masakan m = new masakan();
            this.stat = k.getCon().prepareStatement("insert into masakan values(?,?,?,?)");
            stat.setInt(1, 0);
            if (m.nama_masakan.isEmpty()){
                JOptionPane.showMessageDialog(null, "NAMA MASAKAN TIDAK BOLEH KOSONG");
                return;
            }
            stat.setString(2, m.nama_masakan);
            if(m.harga==0){
                JOptionPane.showMessageDialog(null, "HARGA TIDAK BOLEH KOSONG");
                return;
            }
            stat.setInt(3, m.harga);
            stat.setString(4, m.status);
            stat.executeUpdate();
            refreshTable();
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_BTN_INPUTActionPerformed

    private void TABLE_MASAKANMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLE_MASAKANMouseClicked
        TXT_IDMASAKAN.setText(model.getValueAt(TABLE_MASAKAN.getSelectedRow(), 0).toString());
        TXT_NAMAMASAKAN.setText(model.getValueAt(TABLE_MASAKAN.getSelectedRow(), 1).toString());
        TXT_HARGA.setText(model.getValueAt(TABLE_MASAKAN.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_TABLE_MASAKANMouseClicked

    private void BTN_UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_UPDATEActionPerformed
        try {
            masakan m = new masakan();
            this.stat = k.getCon().prepareStatement("update masakan set nama_masakan=?,"
                    + "harga=?,status=? where id_masakan=?");
            stat.setString(1, m.nama_masakan);
            stat.setInt(2, m.harga);
            stat.setString(3, m.status);
            stat.setInt(4, Integer.parseInt(TXT_IDMASAKAN.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_BTN_UPDATEActionPerformed

    private void BTN_DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DELETEActionPerformed
        try {
            masakan m = new masakan();
            this.stat = k.getCon().prepareStatement("delete from masakan where id_masakan=?");
            stat.setInt(1, Integer.parseInt(TXT_IDMASAKAN.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_BTN_DELETEActionPerformed

    private void BTN_REGISTRASIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REGISTRASIActionPerformed
        MenuRegistrasi reg = new MenuRegistrasi();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_REGISTRASIActionPerformed

    private void BTN_TRANSAKSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_TRANSAKSIActionPerformed
        MenuTransaksi tran = new MenuTransaksi();
        tran.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_TRANSAKSIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMasakan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTN_DELETE;
    public javax.swing.JButton BTN_INPUT;
    public javax.swing.JButton BTN_LOGOUT;
    public javax.swing.JButton BTN_REGISTRASI;
    public javax.swing.JButton BTN_TRANSAKSI;
    public javax.swing.JButton BTN_UPDATE;
    private javax.swing.JComboBox<String> COMBO_STATUS;
    private javax.swing.JTable TABLE_MASAKAN;
    private javax.swing.JTextField TXT_HARGA;
    private javax.swing.JTextField TXT_IDMASAKAN;
    private javax.swing.JTextField TXT_NAMAMASAKAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
