package new_kasir;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Faiz
 */
public class MenuTransaksi extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
    

    /**
     * Creates new form MenuMasakan
     */
    public MenuTransaksi() {
        initComponents();
        setLocationRelativeTo(this);
        k.connect();
        RefreshTable();
        refreshCombo();
       
    }
    class transaksi extends MenuTransaksi{
        int id_transaksi, id_masakan, harga, jumlah_beli, total_bayar;
        String nama_pelanggan, tanggal, nama_masakan;
        
        public transaksi(){
            this.nama_pelanggan = TXT_NAMAPELANGGAN.getText();
            String combo = COMBO_IDMASAKAN.getSelectedItem().toString();
            String[] arr = combo.split(":");
            this.id_masakan = Integer.parseInt(arr[0]);
            try {
                Date date = TXT_TANGGAL.getDate();
                DateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
                this.tanggal = dateformat.format(date);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            this.nama_masakan = arr[1];
            this.harga = Integer.parseInt(arr[2]);
            this.jumlah_beli = Integer.parseInt(TXT_JUMLAHBELI.getText());
            this.total_bayar = this.harga * this.jumlah_beli;
            
                    
            
        }
    }
    
    public void RefreshTable(){
        model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Nama Pelanggan");
        model.addColumn("ID Masakan");
        model.addColumn("Tanggal");
        model.addColumn("Nama Masakan");
        model.addColumn("Harga");
        model.addColumn("Jumlah Beli");
        model.addColumn("Total Bayar");
        TABLE_TRANSAKSI.setModel(model);
        try {
            this.stat = k.getCon().prepareStatement("SELECT * FROM `transaksi`");
            this.rs = this.stat.executeQuery();
            while (rs.next()){
                Object[] data = {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                };
                model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        TXT_IDTRANSAKSI.setText("");
        TXT_NAMAPELANGGAN.setText("");
        TXT_JUMLAHBELI.setText("");
        TXT_TOTALBAYAR.setText("");
        
    }
    
    public void refreshCombo(){
        try {
            this.stat = k.getCon().prepareStatement("SELECT * FROM `masakan` "
                    + "where status='Tersedia'");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                COMBO_IDMASAKAN.addItem(rs.getString("id_masakan")+":"+rs.getString("nama_masakan")+":"+rs.getString("harga"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TXT_IDTRANSAKSI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXT_NAMAPELANGGAN = new javax.swing.JTextField();
        TXT_JUMLAHBELI = new javax.swing.JTextField();
        COMBO_IDMASAKAN = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE_TRANSAKSI = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_input = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_bayar = new javax.swing.JButton();
        BTN_LOGOUT = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TXT_TOTALBAYAR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BTN_MENU = new javax.swing.JButton();
        TXT_TANGGAL = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel2.setText("ID TRANSAKSI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 228, -1));

        TXT_IDTRANSAKSI.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        TXT_IDTRANSAKSI.setEnabled(false);
        getContentPane().add(TXT_IDTRANSAKSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 374, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel3.setText("NAMA PELANGGAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 228, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel4.setText("ID MASAKAN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 228, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel5.setText("TANGGAL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 228, -1));

        TXT_NAMAPELANGGAN.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        getContentPane().add(TXT_NAMAPELANGGAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 374, -1));

        TXT_JUMLAHBELI.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        getContentPane().add(TXT_JUMLAHBELI, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 374, -1));

        COMBO_IDMASAKAN.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        getContentPane().add(COMBO_IDMASAKAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 220, 41));

        TABLE_TRANSAKSI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TABLE_TRANSAKSI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLE_TRANSAKSIMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLE_TRANSAKSI);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 716, 150));

        btn_input.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btn_input.setText("INPUT");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_bayar.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btn_bayar.setText("BAYAR");
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_input, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_input, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 680, -1));

        BTN_LOGOUT.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        BTN_LOGOUT.setText("LOGOUT");
        BTN_LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LOGOUTActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 146, 45));

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel7.setText("JUMLAH BELI");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 228, 40));

        TXT_TOTALBAYAR.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        TXT_TOTALBAYAR.setEnabled(false);
        getContentPane().add(TXT_TOTALBAYAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 374, -1));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSAKSI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 400, 73));

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel8.setText("TOTAL BAYAR");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 228, -1));

        BTN_MENU.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        BTN_MENU.setText("MENU");
        BTN_MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MENUActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 146, 40));
        getContentPane().add(TXT_TANGGAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 230, 374, 33));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Downloads\\Coklat muda lucu estetik gambar makanan imut wallpaper desktop.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
            try {
            transaksi tran = new transaksi();
            TXT_TOTALBAYAR.setText(""+tran.total_bayar);
            String input = JOptionPane.showInputDialog(null, "Masukkan jumlah uang yang dibayarkan:");
            int uangDibayarkan = Integer.parseInt(input);
            int kembalian = uangDibayarkan - tran.total_bayar;            
            if (kembalian < 0) {
            JOptionPane.showMessageDialog(null, "Uang yang dimasukkan kurang!");
            return;
            }
            JOptionPane.showMessageDialog(null, "Kembalian: " + kembalian);
            JOptionPane.showMessageDialog(null, "Kembalian: " + kembalian);
            int pilihan = JOptionPane.showConfirmDialog(null, "apakah anda yakin ingin melakukan pembayaran?",
                    "Konfirmasi pembayaran", JOptionPane.YES_NO_OPTION);
            if (pilihan == JOptionPane.YES_OPTION) {
                this.stat = k.getCon().prepareStatement("INSERT INTO transaksi VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
                this.stat.setInt(1, 0);
                this.stat.setString(2, tran.nama_pelanggan);
                this.stat.setInt(3, tran.id_masakan);
                this.stat.setString(4, tran.tanggal);
                this.stat.setString(5, tran.nama_masakan);
                this.stat.setInt(6, tran.harga);
                this.stat.setInt(7, tran.jumlah_beli);
                this.stat.setInt(8, tran.total_bayar);
                this.stat.executeUpdate();
                RefreshTable();
                JOptionPane.showMessageDialog(null, "pembayaran berhasil");                                
            } else {
                JOptionPane.showMessageDialog(null, "pembayaran dibatalkan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void BTN_LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LOGOUTActionPerformed
        login l = new login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_LOGOUTActionPerformed

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        try {
            transaksi tran = new transaksi();
            TXT_TOTALBAYAR.setText(""+tran.total_bayar);
            this.stat = k.getCon().prepareStatement("insert into transaksi values(?,?,?,?,?,?,?,?)");
            this.stat.setInt(1, 0);
            if(tran.nama_pelanggan.isEmpty()){
                JOptionPane.showMessageDialog(null, "NAMA PELANGGAN TIDAK BOLEH KOSONG");
                return;
            }
            this.stat.setString(2, tran.nama_pelanggan);
            this.stat.setInt(3, tran.id_masakan);
            this.stat.setString(4, tran.tanggal);
            this.stat.setString(5, tran.nama_masakan);
            this.stat.setInt(6, tran.harga);
            if(tran.jumlah_beli==0){
                JOptionPane.showMessageDialog(null, "JUMLAH BELI TIDAK BOLEH KOSONG");
                return;
            }
            this.stat.setInt(7, tran.jumlah_beli);
            this.stat.setInt(8, tran.total_bayar);
            int pilihan = JOptionPane.showConfirmDialog(null, "Tanggal : "+ tran.tanggal+
                    "\nNama Pelanggan : "+tran.nama_pelanggan+
                    "\nPembelian : "+tran.jumlah_beli+" "+tran.nama_masakan+
                    "\nTotal Bayar : "+tran.total_bayar+"\n",
                    "Tambahkan transaksi?",
                    JOptionPane.YES_NO_OPTION);
            if (pilihan == JOptionPane.YES_OPTION) {
                this.stat.executeUpdate();
                RefreshTable();
            }else if (pilihan == JOptionPane.NO_OPTION){
                RefreshTable();
            }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_inputActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
           transaksi tran = new transaksi();
           tran.id_transaksi = Integer.parseInt(TXT_IDTRANSAKSI.getText());
           this.stat = k.getCon().prepareStatement("update transaksi set nama_pelanggan=?,"
                   + "id_masakan=?,tanggal=?,nama_masakan=?,harga=?,jumlah_beli=?,total_bayar=? "
                   + "wherei id_transaksi=?");
           this.stat.setString(1, tran.nama_pelanggan);
           this.stat.setInt(2, tran.id_masakan);
           this.stat.setString(3, tran.tanggal);
           this.stat.setString(4, tran.nama_masakan);
           this.stat.setInt(5, tran.harga);
           this.stat.setInt(6, tran.jumlah_beli);
           this.stat.setInt(7, tran.total_bayar);
           this.stat.setInt(8, tran.id_transaksi);
           this.stat.executeUpdate();
           RefreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void TABLE_TRANSAKSIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLE_TRANSAKSIMouseClicked
        TXT_IDTRANSAKSI.setText(model.getValueAt(TABLE_TRANSAKSI.getSelectedRow(), 0).toString());
        TXT_NAMAPELANGGAN.setText(model.getValueAt(TABLE_TRANSAKSI.getSelectedRow(), 1).toString());
        TXT_JUMLAHBELI.setText(model.getValueAt(TABLE_TRANSAKSI.getSelectedRow(), 6).toString());
        TXT_TOTALBAYAR.setText(model.getValueAt(TABLE_TRANSAKSI.getSelectedRow(), 7).toString());
    }//GEN-LAST:event_TABLE_TRANSAKSIMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            transaksi tran = new transaksi();
            tran.id_transaksi = Integer.parseInt(TXT_IDTRANSAKSI.getText());
            this.stat = k.getCon().prepareStatement("delete from transaksi "
                    + "where id_transaksi=?");
            this.stat.setInt(1, tran.id_transaksi);
            this.stat.executeUpdate();
            RefreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void BTN_MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MENUActionPerformed
        MenuMasakan masak = new MenuMasakan();
        masak.setVisible(true);
        this.setVisible(false);
        masak.BTN_DELETE.setEnabled(true);
        masak.BTN_INPUT.setEnabled(true);
        masak.BTN_UPDATE.setEnabled(true);
        masak.BTN_TRANSAKSI.setEnabled(true);
        
    }//GEN-LAST:event_BTN_MENUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTN_LOGOUT;
    public javax.swing.JButton BTN_MENU;
    private javax.swing.JComboBox<String> COMBO_IDMASAKAN;
    private javax.swing.JTable TABLE_TRANSAKSI;
    public javax.swing.JTextField TXT_IDTRANSAKSI;
    private javax.swing.JTextField TXT_JUMLAHBELI;
    private javax.swing.JTextField TXT_NAMAPELANGGAN;
    private com.toedter.calendar.JDateChooser TXT_TANGGAL;
    public javax.swing.JTextField TXT_TOTALBAYAR;
    public javax.swing.JButton btn_bayar;
    public javax.swing.JButton btn_delete;
    public javax.swing.JButton btn_input;
    public javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
